### ISSUE TITLE
Sample of gazebo

### ISSUE THREAD

**Issue by suguruhamada1003910** [ezWheelSAS/swd_starter_kit_description#4]
Readme is saying "This ROS package contains URDF file to use SWD Starter kit with ROS 1. The URDF contains also contains the collision model and is suitable for Gazebo simulations.".

Do you have sample of gazebo package for SWD?

**Comment by ez-Support** [comment]
You can use the meshes and the urdf we provide to create your own Gazebo model (.sdf).

https://github.com/ezWheelSAS/swd_starter_kit_description/tree/main/meshes 
https://github.com/ezWheelSAS/swd_starter_kit_description/tree/main/urdf

Tutorial:
http://classic.gazebosim.org/tutorials?tut=ros_urdf&cat=connect_ros

Feel free to share to model you created with the community after that.

**Comment by suguruhamada1003910** [comment]
@ez-Support 

Thank you for information!!
