### ISSUE TITLE
Simulation of the swd_starter_kit

### ISSUE THREAD

**Issue by ayoubnaitchrif** [ezWheelSAS/swd_starter_kit_description#5]
Hello, 
I am trying to create a gazebo simulator for the robot, using this package, so I can test different programs before implementing them on the robot, , but but the links seem to be out of place like you can see in the next picture:
![image](https://github.com/ezWheelSAS/swd_starter_kit_description/assets/125379454/e724a5eb-5526-4548-90c1-9563a077b691)

Can you, please, help me with this?
Thanks in advance.

**Comment by ayoubnaitchrif** [comment]
Also, what am I supposed to see after running the gazebo.launch file, because I don't get any error but I still see nothing but the empty world. Thanks for helping.

**Comment by GMezWheel** [comment]
Hi @ayoubnaitchrif,

This launcher spawns an entity swd_starterkit at 0,0,0 into an empty world.
=> but I confirm that no starterkit is displayed

I think that there is an error into the urdf.
```
ezwdev@ezwdev-VM: ros_ws $ ign sdf -p src/swd_starter_kit_description/urdf/swd_starter_kit.urdf 
<sdf version='1.7'>
  <model name='swd_starter_kit'/>
</sdf>
ezwdev@ezwdev-VM: ros_ws $ cat ~/.sdformat/sdformat.log
````
Dbg [parser_urdf.cc:418] Fixed Joint Reduction: extension lumping from [lidar_link] to [base_link]
Dbg [parser_urdf.cc:418] Fixed Joint Reduction: extension lumping from [swd_left_link] to [base_link]
Dbg [parser_urdf.cc:418] Fixed Joint Reduction: extension lumping from [swd_right_link] to [base_link]
**Dbg [parser_urdf.cc:2627] urdf2sdf: link[base_link] has no inertia, [3] children links ignored.
Dbg [parser_urdf.cc:2635] urdf2sdf: link[base_link] has no inertia, [3] children joints ignored.
Dbg [parser_urdf.cc:2649] urdf2sdf: link[base_link] has no inertia, not modeled in sdf**
Dbg [parser.cc:420] parse from urdf file [/disk1/workspace-ezw/ros_ws/src/swd_starter_kit_description/urdf/swd_starter_kit.urdf].

I'll try to fix it as soon as possible.

**Comment by GMezWheel** [comment]
I confirm that inertia is missing for each links:
If I had them into urdf file, the entity is spawn.

Quick fix:
```
...
<link name="swd_right_link">
    <inertial>    
      <mass value="1"/>
      <inertia ixx="1" ixy="0.0" ixz="0.0" iyy="1" iyz="0.0" izz="1"/>
    </inertial>
  </link>
  ...
```
![image](https://github.com/ezWheelSAS/swd_starter_kit_description/assets/92363736/018542da-3e5f-47ff-ab05-48f79c847280)

**Comment by GMezWheel** [comment]
> Hello, I am trying to create a gazebo simulator for the robot, using this package, so I can test different programs before implementing them on the robot, , but but the links seem to be out of place like you can see in the next picture: ![image](https://user-images.githubusercontent.com/125379454/239914836-e724a5eb-5526-4548-90c1-9563a077b691.png)
> 
> Can you, please, help me with this? Thanks in advance.

I confirm that the TF for each links are not well computed.
=> each links have negative z values instead of positive values

I'll try to fix it as soon as possible.

**Comment by ayoubnaitchrif** [comment]
> I confirm that inertia is missing for each links: If I had them into urdf file, the entity is spawn.
> 
> Quick fix:
> 
> ```
> ...
> <link name="swd_right_link">
>     <inertial>    
>       <mass value="1"/>
>       <inertia ixx="1" ixy="0.0" ixz="0.0" iyy="1" iyz="0.0" izz="1"/>
>     </inertial>
>   </link>
>   ...
> ```
> 
> ![image](https://user-images.githubusercontent.com/92363736/241149568-018542da-3e5f-47ff-ab05-48f79c847280.png)

Thank you, I appreciate your help



> > Hello, I am trying to create a gazebo simulator for the robot, using this package, so I can test different programs before implementing them on the robot, , but but the links seem to be out of place like you can see in the next picture: ![image](https://user-images.githubusercontent.com/125379454/239914836-e724a5eb-5526-4548-90c1-9563a077b691.png)
> > Can you, please, help me with this? Thanks in advance.
> 
> I confirm that the TF for each links are not well computed. => each links have negative z values instead of positive values
> 
> I'll try to fix it as soon as possible.

Thanks, please let me know if you find how we can fix it.

**Comment by GMezWheel** [comment]
The URDF file hase been updated.
cf. https://github.com/ezWheelSAS/swd_starter_kit_description/pull/6
